### PR TITLE
[irods/irods#6073] Bumped version to 4.2.12 (4-2-stable)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by korydraughn** [comment]
#'d

**Comment by alanking** [comment]
Should we hold off on this in light of our release plans, or just go ahead and bump it?

**Comment by trel** [comment]
i think i vote bump it, b/c we'll forget and then confuse ourselves later.   we can always come back and branch and... whatever.

**Comment by alanking** [comment]
Sold

**Pull request merged**
