### PR TITLE
[irods/irods#7531] bump irods version requirement and remove exact requirement (main)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
In service of irods/irods#7531

Merge irods/irods#7535 before merging this.

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]

**Review by alanking — APPROVED** [review]
\# it when ready

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by alanking** [comment]
Before I merge this, I just want to ask...

The minimum required CMake version on 4-3-stable is going to be higher than it is on main due to the use of the version ranges in that branch. I think that's okay, but just wanted to say it out loud before merging. Are we okay with that situation?

**Comment by SwooshyCueb** [comment]
I'm fine with it. We have 3.21 in our externals.

**Comment by korydraughn** [comment]
That sounds fine. If we run into issues, we can always bump the cmake minimum version.

**Comment by alanking** [comment]
Yep, sounds good. It is written. Mergin.

**Pull request merged**
