### PR TITLE
[irods/irods#7220] Do not explicitly build against libc++

### PR DESCRIPTION
**Pull request by SwooshyCueb**
In service of irods/irods#7220

Merge irods/irods#7526 before merging this.

### CODE REVIEW

**Comment by SwooshyCueb** [comment]
\#'d

**Review by alanking — COMMENTED** [review]
Do we need to keep the libcxx option around, or are we just moving ahead in the plugins?

If we are keeping the option around, we may need to do the libcxx-variant externals conditional thingy, like we did in irods/irods. I guess for the build hook we can just pick a lane (libstdcxx, it seems), so we are good there.

Just wanted to make sure this is what we wanted before proceeding.

**Comment by SwooshyCueb** [comment]
> Do we need to keep the libcxx option around, or are we just moving ahead in the plugins?

I wasn't planning on supporting it in the plugins

**Comment by SwooshyCueb** [comment]
> I take it the 4-3-stable branch's build/test hooks will be updated to list the libcxx variants instead?

You've already approved the PR for it.

**Review by alanking — APPROVED** [review]
Okay, moving ahead, then.

**Pull request merged**
