### PR TITLE
[irods/irods#6412] Bump version to 4.3.1 (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Review by SwooshyCueb — APPROVED** [review]

**Comment by trel** [comment]
this seems correct - i see three other PRs that we should eyeball as well.

**Review by alanking — COMMENTED** [review]
@trel - Should we look at those before bumping?

**Comment by korydraughn** [comment]
2 of those are for 4.2. The other one is the stage 2 refactor effort planned by @SwooshyCueb.

I think we're good.

**Review by alanking — APPROVED** [review]
Then # it, I say

**Comment by korydraughn** [comment]
#'d

**Pull request merged**
