### PR TITLE
[156] Do not install unittest-xml-reporting==1.14.0 (main)

### PR DESCRIPTION
**Pull request by FifthPotato**
Needed for fixing tests.

### CODE REVIEW

**Review by alanking — APPROVED** [review]
\# it if tests are running / passing

**Review by korydraughn — APPROVED** [review]

**Comment by korydraughn** [comment]
@FifthPotato Is this a cherry-pick of #159?

If yes, pound it.

**Comment by korydraughn** [comment]
For future PRs, always include a statement about "cherry-picking" if that's what happened.

**Comment by FifthPotato** [comment]
> For future PRs, always include a statement about "cherry-picking" if that's what happened.

Octothorpe'd. And yeah, my bad, it was because I opened this one prior to the 4-3-stable one, so I did this one, then 4-3-stable, then tested 4-3-stable, then came back to this (all were the same change).

...So it's a cherry-pick of a cherry-pick, I guess?

**Pull request merged**
